version: '3'

services:
  nginx: 
    image: "nginx:1.15"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./html/:/usr/share/nginx/html/
    ports:
      - "80:80"
    restart: "always"
    links: 
      - "php-fpm"
  php-fpm:
    image: "php:7.2-fpm"
    volumes:
      - ./html/:/usr/share/nginx/html/
  