version: '3'

services:
  httpd-php: 
    #image: php:7.2-apache
    build: 
      context: ./docker/
      dockerfile: Dockerfile
    container_name: 'httpd-php'
    volumes:
      - "./html:/var/www/html"
    ports:
      - 80:80
      - 443:443
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7.25
    command: "--explicit_defaults_for_timestamp --innodb-use-native-aio=0"
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      #MYSQL_ROOT_PASSWORD: 
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: 
      MYSQL_USER: scott
      MYSQL_PASSWORD: tiger
